aws_region     = "us-east-1"
ami_name       = "mi-ami-nginx-nodejs"
instance_type  = "t2.micro"
key_name       = "my-key-pair"
instance_name  = "nginx-nodejs-instance"
aws_access_key = "TU_ACCESS_KEY"
aws_secret_key = "TU_SECRET_KEY"
aws_session_token = "TU_SESSION_TOKEN"