azure_client_id       = "your_azure_client_id"
azure_client_secret   = "your_azure_client_secret"
azure_subscription_id = "your_azure_subscription_id"
azure_tenant_id       = "your_azure_tenant_id"
azure_location        = "East US"
ami_name              = "azure-node-nginx-image"
resource_group_name   = "myResourceGroup"